# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 20:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0003_auto_20190903_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathreport',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
