# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-02 20:25
from __future__ import unicode_literals

from django.db import migrations


sql = 'ALTER TABLE dr_deathreport ALTER COLUMN data TYPE JSONB USING data::JSONB'
reverse_sql = 'ALTER TABLE dr_deathreport ALTER COLUMN data TYPE JSON USING data::JSON'


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0003_auto_20190903_1221'),
    ]

    operations = [
        migrations.RunSQL(
            sql=sql, reverse_sql=reverse_sql
        )
    ]
