# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0005_auto_20211123_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthregistration',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
