# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'The common name given to the facility', max_length=100)),
                ('code', models.CharField(help_text=b'code used to represent this facility', max_length=15)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text=b'Name of location', max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('population', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text=b'The physical latitude of this location', max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text=b'The physical longitude of this location', max_digits=8, null=True)),
                ('lft', models.PositiveIntegerField(blank=True, db_index=True, default=0)),
                ('rgt', models.PositiveIntegerField(blank=True, db_index=True, default=0)),
                ('tree_id', models.PositiveIntegerField(blank=True, db_index=True, default=0)),
                ('level', models.PositiveIntegerField(blank=True, db_index=True, default=0)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text=b'The parent of this Location. Although it is not enforced, itis expected that the parent will be of a different LocationType', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.Location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Type',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.LocationType'),
        ),
        migrations.AddField(
            model_name='facility',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='locations.Location'),
        ),
    ]
