# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20190903_1224'),
    ]

    query = '''
    INSERT INTO
        locations_facility (name, code, location_id)
    SELECT
        loc.name, loc.code, loc.id
    FROM
        locations_location AS loc
    JOIN
        locations_locationtype AS typ
    ON
        loc.type_id = typ.id
    WHERE
        typ.name = 'RC';
    '''

    operations = [
        migrations.RunSQL(query)
    ]
