# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-05 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20190923_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='source',
            field=models.CharField(choices=[(b'external', b'External'), (b'internal', b'Internal')], default=b'internal', max_length=32),
        ),
    ]
