# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='vrp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX locations_fulltext_index ON locations_location (name)',),
            ('DROP INDEX locations_fulltext_index ON locations_location',),
        )
    ]
